### ISSUE TITLE
RHOC owned prior to snapshot has no corresponding REV

### ISSUE THREAD

**Issue by Penckm6** [rchain/Governance-Committee#9]
I currently have 21,221.48170303 RHOC in a private wallet to which I have only recently recovered my access. I have held the RHOC in this wallet since the 7th June 2019.
The wallet address is 
0x77D84f3DDBa43874161021eB874c118aeD838f79
I originally purchased 21,281.48170303 RHOC through Coinspot on 23rd April 2019 and transfered to the current wallet once trading of RHOC was suspended in preparation of the issuance of REV.
I tried to locate the issued REV have been advised that there has not been an issue of REV for my currently held RHOC. I would like to have that  investigated. I cannot move or trade my RHOC and I would like to be able to access the value that I currently have in my wallet.
If you need any further evidence or documentation please let me know and I will do whatever I can to solve this situation.
Regards

**Comment by jimscarver** [comment]
@ian-bloom the balance makes no sense to me. No rhoc is unnacounted for in the snapshot.
https://etherscan.io/token/0x168296bb09e24a88805cb9c33356536b980d3fc5?a=0x77D84f3DDBa43874161021eB874c118aeD838f79

How do to resolve this issue?

**Comment by Penckm6** [comment]
Hi. I am wondering if there is any resolution to locating my REV? I would like to know what options I have to recover the value of my investment in RHOC. Has someone else got my REV or is there an option of running a crawler to locate the transactions of my RHOC? Please let me know what options are available to me. Regards

**Comment by jimscarver** [comment]
Apparently your rev is locked on the IDEX contract 0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208

It looks to me that there were no deposits on idex since before the snapshot so you should be entitled to restitution https://etherscan.io/token/0x168296bb09e24a88805cb9c33356536b980d3fc5?a=0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208

Do we all agree? @ian-bloom ?

**Comment by Penckm6** [comment]
Hi. Is there anything further you require from me to resolve this?
Regards

**Comment by Penckm6** [comment]
Hi. Is there anything further you require from me to resolve this?
Regards

**Comment by Penckm6** [comment]
Hi. Would it be possible to finalise this issue? Could I have the deatails of how I access my swapped REV from my original RHOC? Thanks

**Comment by jimscarver** [comment]
> Would it be possible to finalise this issue?

Not for some time. The coop did not support rhoc speculation on exchanges and clearly communicated from the beginning that you must hold the private keys to your rhoc in order to get REV and is under no obligation to recover REV locked in ethereum contract addresses.

At the same time the gov committee has been investigating the possibility returning REV to the uninformed who left rhoc on contracts when it can be proven they deposited the rhoc and did not sell it. Due to the difficulty in doing such a proof manually and potential for mistakes it was suggested that a crawler be constructed to track all the rhoc transactions so that the balances at each point in time are determined and the transfer of rev to true owner account be made automatically.

The recommendation to the board is that they move REV locked in contract addresses into an escrow account at the hard fork and consider taking some percentage of the REV to pay for development of the crawler. There is no urgency to do this soon. Doing it right and considering legal implications returning rev eventually when we can safely means you can expect it to be a long time before you can sell your REV. The coop has many higher priorities. It is best for the coop if you keep it longer anyway and in my view likely to be more rewarding for you. The alternative to not getting it soon is not getting it at all.

Note: there are no plans to recover rev from exchanges that hold the private keys like kucoin, The only way to recover REV for rhoc on those exchanges is to get it from them. Kucoin is refusing to return deposited REV. They are keeping it for themselves.

**Comment by Penckm6** [comment]
Thank you Jim for getting back to me. It all sounds very complicated and a whole lot of work. Just to note that I did act on the early communications and moved my coin prior to the switch into a wallet for which I hold the private key so I'm not sure what else I could have done. Are you advising that, now I have flagged it, that I wait it out? Should I check back with you or someone at a later date?
I really appreciate your help, thank you.
Peter

**Comment by jimscarver** [comment]
At some point we will create a repo in rchain-community for this work. Until then this is the best place to get updates. Do not expect there to be updates in the near future. I do expect you will get you rev eventually less a possible small percentage to cover the cost of recovery. An alternative is that the crawler development could be crowd funded.

**Comment by ian-bloom** [comment]
@Penckm6. On Jun-07-2019 03:14:47 PM (+UTC 21) 221.48170303 RHOC was transferred from 0x77d84f3ddba43874161021eb874c118aed838f79 to IDEX.
([https://etherscan.io/tx/0x38dea5594108b94da63414d0e32d9448e7874574305e96aed6d004e82b1bc676](https://etherscan.io/tx/0x38dea5594108b94da63414d0e32d9448e7874574305e96aed6d004e82b1bc676))

The IDEX balance at the time of the [snapshot](https://github.com/rchain/rchain/blob/43257ddb7b2b53cffb59a5fe1d4c8296c18b8292/wallets_RHOC_BLOCK-9371743.txt#L946) was 13,745.04267036 RHOC

RChain mainnet genesis wallet, [wallets.txt](https://github.com/rchain/rchain/blob/dev/wallets.txt) was [adjusted](https://github.com/rchain/rchain/commit/cf10e26f537e516fb3ebcb5e9b9d77f1e0b907f0#diff-630e77b9c47846cdb77db3e7e194b39eaaa048103f5459fc7f4936153581caf3L946) to remove the IDEX wallet and balance from line 946 because RHOC locked in the IDEX contract were not to be included in the genesis wallet. The 13,745.04267036 RHOC was reclaimed by the Co-op.

I propose that Co-op include IDEX in issue #11 and transfer 13,745.04267036 REV from the Co-op Treasury Reserve wallet into the Co-op "Frozen REV Escrow Wallet" to be later redistributed automatically to the IDEX RHOC holders at Ethereum block 9371743.

**Comment by Penckm6** [comment]
Thank you for the update. Appreciate the effort being put in to correct the missing balances. Is there a reason for the disparity in balances as my IDEX wallet had 21,221.48170303 RHOC from 7th July 2019, but you only have 13,745.04267036 RHOC recognised in the IDEX wallet at the time of the snapshot? Also, do I need to creat a REV wallet to hold my token for when you are able to resolve this issue to ?
Regards

**Comment by ian-bloom** [comment]
@Penckm6.

My previous post (deleted) mistakenly referenced the Ethereum RHOC contract (0x168296bb09e24A88805CB9c33356536B980D3fC5) instead of the IDEX contract (0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208).

On Jun-07-2019 03:14:47 PM (+UTC 21) 21,221.48170303 RHOC was transferred from 0x77d84f3ddba43874161021eb874c118aed838f79 to IDEX (0x2a0c0dbecc7e4d658f48e01e3fa353f44050c208).
([https://etherscan.io/tx/0x38dea5594108b94da63414d0e32d9448e7874574305e96aed6d004e82b1bc676](https://etherscan.io/tx/0x38dea5594108b94da63414d0e32d9448e7874574305e96aed6d004e82b1bc676))

The IDEX balance at the time of the [snapshot](https://github.com/rchain/rchain/blob/76c9ef8835db8dd0c0884be0c1ff002749632055/wallets_RHOC_BLOCK-9371743.txt#L366) was 335,420.49164080 RHOC.

Issue #11 outlines a process for automated redistribution of RChain REV for RHOC held within the DEX at block 9371743 minus any recovery fees assessed by RChain Co-op.

When this process is complete, REV will be distributed to you at REV address [1111Zz6QpE2q2R5Skpys7JWt6p6Qt295h6ywwV9zvXabmdFndjzcm](https://revdefine.io/#/revaccounts/1111Zz6QpE2q2R5Skpys7JWt6p6Qt295h6ywwV9zvXabmdFndjzcm). This RChain address corresponds to the 0x77d84f3ddba43874161021eb874c118aed838f79 address that you control on Ethereum, and can be accessed using the same private key. (You don't have to create a new REV wallet.)
